# -*- coding: utf-8 -*-
"""Test.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kofhfSU4y6Y1lsld-nh4VunKqgFEL2M
"""

print("Hello")

print("Test")